image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - yarn electron:build --win appx nsis

artifacts:
  - path: dist_electron/*.exe
    name: navfit
  - path: dist_electron/*.appx
    name: navfit

branches:
  only:
    - prod

deploy:
  - provider: GitHub
    description: 'AppVeyor Release'
    auth_token:
      secure: fEkXGI1MwwnXikl6PyKr9q8U1Dcgw+yZuPznmh/YqHS4QtwLBkqxl0C4cDwB1vVf
    draft: true
    artifact: navfit2020
    force_update: true
    on:
      branch: prod

test: off
