image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - yarn electron:build

artifacts:
  - path: build\staging\*.exe
    name: navfit2020

before_deploy:
  - sh: export VERSION="$(node -p "require('./package.json').version")"

deploy:
  - tag: $(VERSION)
    provider: GitHub
    description: 'AppVeyor Release'
    auth_token:
      secure: fEkXGI1MwwnXikl6PyKr9q8U1Dcgw+yZuPznmh/YqHS4QtwLBkqxl0C4cDwB1vVf
    draft: true
    force_update: true
    on:
      branch: prod

test: off
