version: 2.1

orbs:
  github-release: h-matsuo/github-release@0.1.3
#  cypress: cypress-io/cypress@1

executors:
  windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: /tmp/workspace
  mac:
    macos:
      xcode: 12.2.0
    working_directory: /tmp/workspace
  github:
    docker:
      - image: cibuilds/github:0.10
    working_directory: /tmp/workspace

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test

  build_windows_linux:
    executor: windows
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build -wl
      - run:
          name: Remove non-binary files
          shell: /bin/sh
          command: |
            cd ./dist_electron
            ls
            rm -rf bundled linux-unpacked win-unpacked .icon-ico
            rm *.yml *.blockmap
            ls
      - store_artifacts:
          path: dist_electron

  build_macos:
    executor: mac
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build --mac
      - store_artifacts:
          path: dist_electron

  publish-github-release:
    executor: github
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: View files
          shell: /bin/sh
          command: |
            ls
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c ${CIRCLE_SHA1} -delete v$CIRCLE_BUILD_NUM $CIRCLE_ARTIFACTS/ || true

workflows:
  build:
    jobs:
      - test
#      - cypress/run:
#          yarn: true
#          record: true
      - build_windows_linux:
          requires:
            - test
            #- cypress/run
#      - build_macos:
#          requires:
#            - test
#            #- cypress/run
      - publish-github-release:
          requires:
            - test
            #- cypress/run
            - build_windows_linux
#            - build_macos
