version: 2.1

orbs:
  github-release: h-matsuo/github-release@0.1.3

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn && yarn lint
      - run: yarn test
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn electron:build -wl
      - store_artifacts:
          path: ./dist_electron/*.exe
      - store_artifacts:
          path: ./dist_electron/*.snap
      - store_artifacts:
          path: ./dist_electron/*.appImage
  build_macos:
    macos:
      xcode: "12"
    steps:
      - checkout
      - run: yarn && yarn electron:build --mac
      - store_artifacts:
          path: ./dist_electron/*.dmg
  publish-github-release:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - github-release/create:
          tag: vX.Y.Z
          title: Version vX.Y.Z
          description: This release is version vX.Y.Z .
          file-path: ./dist_electron

workflows:
  windows:
    jobs:
      - test
      - publish-github-release
      - build_windows:
          requires:
            - test
      - publish-github-release:
          requires:
            - test
            - build_windows
  #macos:
    #jobs:
      #- test
      #- build_macos:
          #requires:
            #- test
