version: 2.1

orbs:
  github-release: h-matsuo/github-release@0.1.3
  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test

  build_windows_linux:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build -wl
      - store_artifacts:
          path: ./dist_electron

  build_macos:
    macos:
      xcode: "12"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build --mac
      - store_artifacts:
          path: ./dist_electron

  publish-github-release:
    description: CircleCi release `v$TAG`.
    executor: github-release/default
    steps:
      - github-release/create:
          tag: v$TAG
          title: Version v$TAG
          description: This release is version v$TAG .
          file-path: ./dist_electron

workflows:
  windows_linux:
    jobs:
      - test
      - cypress/run:
          yarn: true
          record: true
      - build_windows_linux:
          requires:
            - test
            - cypress/run
      - publish-github-release:
          requires:
            - test
            - cypress/run
            - build_windows_linux
#  macos:
#    jobs:
#       - test
#       - cypress/run:
#           yarn: true
#           record: true
#       - build_macos:
#           requires:
#             - test
#             - cypress/run
#       - publish-github-release:
#           requires:
#             - test
#             - cypress/run
#             - build_macos
