version: 2.1

orbs:
  github-release: h-matsuo/github-release@0.1.3
#  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test

  build_windows_linux:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build -wl
      - run:
          shell: /bin/sh
          command: |
            echo Removing non-executable files
            cd /root/project/dist_electron
            ls
            rm -rf bundled linux-unpacked
            rm *.yml *.blockmap
            ls
      - store_artifacts:
          path: /root/project/dist_electron

  build_macos:
    macos:
      xcode: 12.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build --mac
      - store_artifacts:
          path: /root/project/dist_electron

  publish-github-release:
    description: CircleCi release `v$TAG`.
    executor: github-release/default
    steps:
      - github-release/create:
          tag: v$TAG
          title: Version v$TAG
          description: This release is version v$TAG .
          file-path: /root/project/dist_electron

workflows:
  build:
    jobs:
      - test
#      - cypress/run:
#          yarn: true
#          record: true
      - build_windows_linux:
          requires:
            - test
            #- cypress/run
#      - build_macos:
#          requires:
#            - test
#            #- cypress/run
      - publish-github-release:
          requires:
            - test
            #- cypress/run
            - build_windows_linux
#            - build_macos
