version: 2.1

orbs:
  github-release: h-matsuo/github-release@0.1.3
#  cypress: cypress-io/cypress@1

executors:
  windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: /tmp/workspace
  mac:
    macos:
      xcode: 12.2.0
    working_directory: /tmp/workspace

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test

  build_windows_linux:
    executor: windows
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build -wl
      - run:
          name: Remove non-binary files
          shell: /bin/sh
          command: |
            cd ./dist_electron
            ls
            rm -rf bundled linux-unpacked win-unpacked .icon-ico
            rm *.yml *.blockmap
            ls
      - persist_to_workspace:
          root: ./
          paths:
            - dist_electron

  build_macos:
    executor: mac
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn electron:build --mac
      - persist_to_workspace:
          root: ./
          paths:
            - dist_electron

  publish-github-release:
    description: CircleCi release `v$TAG`.
    executor: github-release/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - github-release/create:
          tag: vX.Y.Z
          title: Version vX.Y.Z
          description: This release is version vX.Y.Z.
          file-path: ./dist_electron
          draft: true

workflows:
  build:
    jobs:
      - test
#      - cypress/run:
#          yarn: true
#          record: true
      - build_windows_linux:
          requires:
            - test
            #- cypress/run
#      - build_macos:
#          requires:
#            - test
#            #- cypress/run
      - publish-github-release:
          requires:
            - test
            #- cypress/run
            - build_windows_linux
#            - build_macos
