name: navfit
version: git
summary: Navy Evaluation/Fitrep Writer Modernized
description: |
 Navy evaluation and FITREP creation application to replace NavFit98. Allows for
 adding, editing, deleting, and exporting to offical US Navy NAVPERS PDF's.
type: app
grade: devel
confinement: strict

parts:
  navfit:
    plugin: nodejs
    source-branch: prod
