name: navfit
version: git
summary: Navy Evaluation/Fitrep Writer Modernized
description: |
 Navy evaluation and FITREP creation application to replace NavFit98. Allows for
 adding, editing, deleting, and exporting to offical US Navy NAVPERS PDF's.
base: core18
confinement: strict
grade: stable

apps:
  navfit:
    command: bin/desktop-launch
    desktop: usr/share/applications/rpcs3.desktop

parts:
  navfit:
    plugin: nodejs
    nodejs-version: 10.23.0
    source: .
    source-branch: prod
